### ISSUE TITLE
The code generated by ChatGPT may replicate existing code

### ISSUE THREAD

**Issue by Thompson-cyber** [villesalmela/ot-harjoitustyo#1]
**Description**: 

Hi ,I found a potential issue regarding license violation in the [dns.py](https://github.com/villesalmela/ot-harjoitustyo/blob/main/src/layers/dns.py) . The [DNSRCode and DNSQType Class](https://github.com/villesalmela/ot-harjoitustyo/blob/main/src/layers/dns.py#L16C7-L16C15) generated by ChatGPT may have been derived from another repository with GPL-2.0 license. Below are the details:
## Details

The code  ```class DNSQType(EnumProperty):``` and [```class DNSRCode(EnumProperty):```](https://github.com/villesalmela/ot-harjoitustyo/blob/main/src/layers/dns.py#L16C7-L16C15) appears to have been generated by GitHub ChatGPTwith [```Generated with ChatGPT```](https://github.com/villesalmela/ot-harjoitustyo/blob/main/src/layers/dns.py#L20C5-L20C28) comments.

However, the code from lines  16 to 91 and lines 109 to 124 seems to be a code clone with [dns_const.py in NFStest](https://github.com/thombashi/NFStest/blob/be1c8634a63a749baf7b8c377dcd92a551af3ea4/packet/application/dns_const.py#L161) and [Status.py in NoobSec-Toolkit](https://github.com/krintoxi/NoobSec-Toolkit/blob/630cd96eb1b6bf850cfb459500cc39410e08be51/NoobSecToolkit%20/tools/harvester/discovery/DNS/Status.py#L18). The main difference between the two code snippets is the comments. Additionally, the ChatGPT generated code was updated on **Apr/28/2024** and the cloned code was updated on **OCT/14/2016**.
https://github.com/villesalmela/ot-harjoitustyo/blob/c73396889810f3958de8b4cc6647d4dd02cdac59/src/layers/dns.py#L16-L91

https://github.com/villesalmela/ot-harjoitustyo/blob/c73396889810f3958de8b4cc6647d4dd02cdac59/src/layers/dns.py#L109-L124

There is no license for the ChatGPT-generated code in  dns.py and the repository. However, the cloned code is under GPL-2.0 license. [GPL-2.0 in NoobSec-Toolkit](https://github.com/krintoxi/NoobSec-Toolkit?tab=GPL-2.0-1-ov-file#readme)  and [GPL-2.0 in NFStest](https://github.com/thombashi/NFStest/blob/master/LICENSE)
According to the conditions of this  [GPL-2.0](https://github.com/krintoxi/NoobSec-Toolkit?tab=GPL-2.0-1-ov-file#readme) license  :

>You may copy and distribute verbatim copies of the Program's source code as you receive it, in any medium, provided that you conspicuously and appropriately publish on each copy an appropriate copyright notice and disclaimer of warranty; keep intact all the notices that refer to this License and to the absence of any warranty; and give any other recipients of the Program a copy of this License along with the Program.

Due to the ChatGPT-generated code having no license and the cloned code being under the  [GPL-2.0](https://github.com/krintoxi/NoobSec-Toolkit?tab=GPL-2.0-1-ov-file#readme)  license, there may be a potential license violation. 

1. How do you view the code clone between ChatGPT-generated code and existing open-source code?
2. Is there a potential license conflict between the [dns.py](https://github.com/villesalmela/ot-harjoitustyo/blob/main/src/layers/dns.py) and the   [dns_const.py in NFStest](https://github.com/thombashi/NFStest/blob/be1c8634a63a749baf7b8c377dcd92a551af3ea4/packet/application/dns_const.py#L161)  and [Status.py in NoobSec-Toolkit](https://github.com/krintoxi/NoobSec-Toolkit/blob/630cd96eb1b6bf850cfb459500cc39410e08be51/NoobSecToolkit%20/tools/harvester/discovery/DNS/Status.py#L18)?
3. If the license violation exists, would you add some explanation about the open-source licenses at the file level or repository level?

Thank you for your attention to this matter.

**Comment by Thompson-cyber** [comment]
Hi, I would greatly appreciate any updates or feedback you can provide when you have a moment. :blush:

**Comment by villesalmela** [comment]
Hi, thanks for bringing this to my attention. As this repo is no longer necessary for me or anyone else to my knowledge, I'll be making it private. I believe this should address any potential license violations.
